# Generated by Django 3.1.6 on 2021-03-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VRApp', '0003_product_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
