# Generated by Django 3.1.6 on 2021-04-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VRApp', '0004_auto_20210312_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
