# Generated by Django 3.1.6 on 2021-04-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VRApp', '0006_auto_20210401_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
